name: Deploy to AWS S3

on:
  push:
    branches:
      - main
      - master
      - github-actions

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Região da AWS onde o bucket está localizado

    - name: Deploy to S3
      run: |
        aws s3 sync ./public s3://nome-do-seu-bucket --delete
